### ISSUE TITLE
开发过程中，经常会出现。（重新运行项目就会好，但是治标不治本）

### ISSUE THREAD

**Issue by 1725476947** [oyjt/uniapp-vue3-template#12]
图片：
![1718847781980](https://github.com/oyjt/uniapp-vue3-template/assets/82707598/2f238f6e-8579-44d6-b607-bead96bd7e07)

代码：
09:16:20.582 开始差量编译...
09:16:22.800 项目 'uniapp-vue3-template' 编译成功。前端运行日志，请另行在小程序开发工具的控制台查看。
09:28:01.871 开始差量编译...
09:28:03.580 项目 'uniapp-vue3-template' 编译成功。前端运行日志，请另行在小程序开发工具的控制台查看。
09:28:46.371 开始差量编译...
09:28:48.099 项目 'uniapp-vue3-template' 编译成功。前端运行日志，请另行在小程序开发工具的控制台查看。
09:28:59.388 node:events:495
09:28:59.394       throw er; // Unhandled 'error' event
09:28:59.401       ^
09:28:59.411 Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
09:28:59.418 Emitted 'error' event on FSWatcher instance at:
09:28:59.424     at FSWatcher._handleError (file:///C:/Users/Administrator/Desktop/lcj/weixin/weixin-template-vue3-ts/uniapp-vue3-template/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/watch.js:4246:10)
09:28:59.431     at NodeFsHandler._boundHandleError (file:///C:/Users/Administrator/Desktop/lcj/weixin/weixin-template-vue3-ts/uniapp-vue3-template/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/watch.js:2720:43)
09:28:59.438     at ReaddirpStream.emit (node:events:517:28)
09:28:59.445     at emitErrorNT (node:internal/streams/destroy:151:8)
09:28:59.453     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
09:28:59.460     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
09:28:59.466   errno: -4082,
09:28:59.473   code: 'EBUSY',
09:28:59.480   syscall: 'lstat',
09:28:59.486   path: 'C:\\pagefile.sys'
09:28:59.493 }
09:28:59.500 Node.js v18.20.2

**Comment by oyjt** [comment]
#6 和这个是一个问题。
解决方案是升级uniapp相关库到最新`alpha`版，使用`vite5.0`。
不想升级，也可以采用 #6 中的临时解决方案。

**Comment by 1725476947** [comment]
谢谢了

**Comment by 1725476947** [comment]
你可以把你的收款码发出来，想请你喝杯咖啡

**Comment by oyjt** [comment]
> 你可以把你的收款码发出来，想请你喝杯咖啡
感谢支持，已在在文档末尾加上了收款码
