### ISSUE TITLE
使用uview-plus组件，编译后微信开发者工具运行样式失效

### ISSUE THREAD

**Issue by EMRZZZ** [oyjt/uniapp-vue3-template#19]
![企业微信截图_1723642505880](https://github.com/user-attachments/assets/2e5b3121-4172-408f-8c2c-67088019d166)

<up-input
placeholder="准备做什么？"
border="none"
font-size="30rpx"
clearable
color="rgb(48, 48, 48)"
/>
<up-icon name="list" size="100rpx" color="red" />
新建项目后在首页使用这两个组件，样式失效，但在h5中运行正常

**Comment by oyjt** [comment]
问题已修复 #20 ，和这个问题相同的原因
