### ISSUE TITLE
request问题

### ISSUE THREAD

**Issue by Ulrica-CH** [oyjt/uniapp-vue3-template#21]
发送网络请求 在 h5 页面上 不能成功发起，network 面板监听不到请求，且没有报错

**Comment by oyjt** [comment]
网络请求相关代码是怎么写的？有没有demo可以提供？
在项目的`src/store/user/inde.ts`中有登录接口的请求实现，可以作为参考

**Comment by Ulrica-CH** [comment]
![Snipaste_2024-08-22_16-28-41](https://github.com/user-attachments/assets/3ed85b88-6121-418e-9198-969f5747461a)
![2](https://github.com/user-attachments/assets/297c75b2-e029-4d1a-86bb-7164963cb846)
# 接口地址
VITE_APP_BASE_API = '.'

**Comment by Ulrica-CH** [comment]
我新拉去项目，然后使用 userstore 的 login 登录也会有问题，network 监听不到

**Comment by oyjt** [comment]
问题已经修复，重新拉代码试试。
原因是`uview-plus`造成的`uni.$u.http`无法挂载，改为`const http= new Request()`实现即可。具体代码可以看`utils/request`里面的相关实现。
问题的具体情况，查看`luch-request`仓库中的这个问题[微信小程序，不支持吗？无法设置baseURL ，h5端能发请求](https://github.com/lei-mu/luch-request/issues/119#top)

**Comment by Ulrica-CH** [comment]
这个可以了，但是我发现interceptors里面的拦截器没有工作,请求 响应拦截器都没有正常工作

**Comment by oyjt** [comment]
> 这个可以了，但是我发现interceptors里面的拦截器没有工作,请求 响应拦截器都没有正常工作

已修复，重新拉下代码。确保拦截器中的`http`和请求的是同一个，项目中只应存在一个`const http = new Request()`实例
