### ISSUE TITLE
自定义 customtab 不会复制coustom-tab-bar目录到编译文件

### ISSUE THREAD

**Issue by fe-room** [oyjt/uniapp-vue3-template#28]

**Comment by oyjt** [comment]
自定义之后，页面有引入吗？不过自定义组件不适用，是不会再编译文件中显示的。因为框架默认做了摇树优化

**Comment by fe-room** [comment]
> 自定义之后，页面有引入吗？不过自定义组件不适用，是不会再编译文件中显示的。因为框架默认做了摇树优化

按照官方的说法在编译的时候如果根目录存在此目录是会直接复制到编译后的目录里的， 用脚手架最新的vite模版好像也是不会复制过去，用hb生成的项目会复制进去。

**Comment by oyjt** [comment]
估计是两者的编译模式不同。如果自定义的组件不使用，为什么还要复制的编译目录？有这样的使用场景吗？
不使用的组件到编译文件，会增加体积，这不太合理吧。

**Comment by fe-room** [comment]
> 估计是两者的编译模式不同。如果自定义的组件不使用，为什么还要复制的编译目录？有这样的使用场景吗？ 不使用的组件到编译文件，会增加体积，这不太合理吧。

小程序的自定义tab 是不需要额外引入的，配置了就生效    在根目录下有这个目录就生效

**Comment by oyjt** [comment]
翻了一下官方的文档，了解了一下这个组件，这个组件相当于官方内置组件，在需要的地方直接使用即可，但使用该组件的地方需要被引入才行。
例如官方文档给的示例是在`windows/top-window.vue`中使用了这个组件，然后在`page.json`中引用了该组件，所以我推测本质上还是需要引入才能够本编译。
