### ISSUE TITLE
pnpm install 报错

### ISSUE THREAD

**Issue by leidao** [oyjt/uniapp-vue3-template#3]
<img width="300" alt="image" src="https://github.com/oyjt/uniapp-vue3-template/assets/39399843/95fbf841-b36e-48db-a8e7-07778d1286c5">
我的node版本是18.16，pnpm版本是7.0.1。

**Comment by oyjt** [comment]
抱的什么错误？有错误日志吗？

**Comment by yulingboy** [comment]
![image](https://github.com/oyjt/uniapp-vue3-template/assets/39452106/d59cc49a-143c-48b4-aef1-64f46561c162)
应该是vite-plugin-imagemin这个插件没装上，这个插件我百度，说是服务器在国外，不好装

**Comment by oyjt** [comment]
如果不需要使用`vite-plugin-imagemin`这个插件移除

**Comment by EMRZZZ** [comment]
我也遇到了，pngquant的下载源连接不上，原因是DNS被污染了，需要手动映射，host添加如下

199.232.28.133 raw.githubusercontent.com
