### ISSUE TITLE
封装的request 打开catch的时候，返回 reject(data)  微信小程序会报错

### ISSUE THREAD

**Issue by goodking-bq** [oyjt/uniapp-vue3-template#30]
![1729520922715](https://github.com/user-attachments/assets/2096d756-2875-41dd-bed6-4388b1c549fd)
导致promise then catch finally 不执行

**Comment by oyjt** [comment]
能贴相关的代码看看吗？

**Comment by goodking-bq** [comment]
1. 这里开启catch
![image](https://github.com/user-attachments/assets/4d194093-8cfa-4e9a-a305-62cb3967f62d)
2.  调用的时候，当需要catch的时候
![image](https://github.com/user-attachments/assets/592d3e70-bae2-44b8-a8de-1ea62f38b7b1)

**Comment by goodking-bq** [comment]
哦   谢谢  晚上回去试试

**Comment by goodking-bq** [comment]
不知道是我写的问题还是什么 。1的配置去掉了 。
下面两种写法是一样的结果 。小程序依然报错
![image](https://github.com/user-attachments/assets/4f510f8c-2e76-4768-a121-756f23fcc093)
![image](https://github.com/user-attachments/assets/23d857d6-9bb0-4cbb-9c4e-2d3e727a8ec0)

注: 小程序开发工具用的最新稳定版

**Comment by oyjt** [comment]
> 谢谢大佬的解答，但是 不知道是我写的问题还是什么 。1的配置去掉了 。 下面两种写法是一样的结果 。小程序依然报错 ![image](https://private-user-images.githubusercontent.com/7803202/380056429-4f510f8c-2e76-4768-a121-756f23fcc093.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTA2NzAsIm5iZiI6MTczMDA5MDM3MCwicGF0aCI6Ii83ODAzMjAyLzM4MDA1NjQyOS00ZjUxMGY4Yy0yZTc2LTQ3NjgtYTEyMS03NTZmMjNmY2MwOTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMDQzOTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmI2YjBiYzBjNjMxOGZlM2E2ODQ1Y2M4ZDU3Yzc5NTZiY2FhNGE3ZDY0Yjk4MjA2MTdmYmZjNDgxYTFhNjYzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.9xU1mHZjHzfwi0dShaWQwfvZdNO5l3ToEt1au5nKqBo) ![image](https://private-user-images.githubusercontent.com/7803202/380057049-23d857d6-9bb0-4cbb-9c4e-2d3e727a8ec0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTA2NzAsIm5iZiI6MTczMDA5MDM3MCwicGF0aCI6Ii83ODAzMjAyLzM4MDA1NzA0OS0yM2Q4NTdkNi05YmIwLTRjYmItOWM0ZS0yZDNlNzI3YThlYzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMDQzOTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzFlMTllMTdjZGQ1NGZkMzgzNDgwYmZhYTU1Mzc0NWVkOGQ2NjE1OWE5MTlmNTI4NDNiMDcwMzk3ZGVjNTA1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.72NPTYUxtV_eIpD2Ibvw2j9tMO4vZLhq-uucJtjNxfs)
> 
> 注: 小程序开发工具用的最新稳定版

还是报一样的错吗？现在代码中的`catch` `finally`有执行了吗？

**Comment by oyjt** [comment]
拉下最新代码再试试
