### ISSUE TITLE
dev环境无法调试

### ISSUE THREAD

**Issue by MelodyLLL** [oyjt/uniapp-vue3-template#31]
需要把  drop: env.VITE_DROP_CONSOLE ? ['console', 'debugger'] : [],  这句完全去掉才会执行断点和打印。暂时不知什么原因

**Comment by MelodyLLL** [comment]
另一问题，微信开发者工具中，启动后第一次修改代码热重载会生效，后面就需要手动点击编译按钮

**Comment by oyjt** [comment]
试了试，没有复现这种情况。执行的运行命令是什么？在`vscode`还是`hxbuilder`中运行的项目

**Comment by oyjt** [comment]
试了试，没有复现这种情况。执行的运行命令是什么？在`vscode`还是`hbuilder x`中运行的项目

**Comment by MelodyLLL** [comment]
> 试了试，没有复现这种情况。执行的运行命令是什么？在`vscode`还是`hbuilder x`中运行的项目

dev:mp-weixin，在vscode下运行的

**Comment by oyjt** [comment]
问题已修复，重新拉下代码试试。
根本原因是，环境变量都是字符串类型，判断永远为`true`所以不能打印`consle`和`debugger`
改写成这样即可解决
```
esbuild: {
  drop: JSON.parse(env.VITE_DROP_CONSOLE) ? ['console', 'debugger'] : [],
}
```

**Comment by MelodyLLL** [comment]
> 问题已修复，重新拉下代码试试。 根本原因是，环境变量都是字符串类型，判断永远为`true`所以不能打印`consle`和`debugger` 改写成这样即可解决
> 
> ```
> esbuild: {
>   drop: JSON.parse(env.VITE_DROP_CONSOLE) ? ['console', 'debugger'] : [],
> }
> ```

调试问题验证ok的。关于热更新的问题，在win11上正常。mac上之前有问题目前看来是正常的
