### ISSUE TITLE
为什么使用uview-plus的组件，在小程序会这么大呢？在 h5 是正常的。

### ISSUE THREAD

**Issue by inccleo** [oyjt/uniapp-vue3-template#32]
![image](https://github.com/user-attachments/assets/fc8ac586-952f-45e8-9c67-3369af1f4f0a)
![image](https://github.com/user-attachments/assets/757413bc-940c-4bb4-8e10-133088f5a6c1)
![image](https://github.com/user-attachments/assets/7f20aa73-8651-4726-875f-3a617a118f13)

**Comment by oyjt** [comment]
父组件有加额外的样式吗？或者审查一下元素看看，是哪里影响到了大小

**Comment by inccleo** [comment]
> 组件父还有额外的样式吗？或者审查一下看看元素，是哪里影响到了大小

**Comment by inccleo** [comment]
![image](https://github.com/user-attachments/assets/ae910b00-14cc-4bd5-a015-fd5c6438ada7)

**Comment by inccleo** [comment]
> 父组件有加额外的样式吗？或者审查一下元素看看，是哪里影响到了大小

没有别的样式，在 h5 是正常显示

**Comment by oyjt** [comment]
这是个bug，已经修复，更新一下版本。
本质原因是在`manifest.json`默认开启合并组件虚拟节点`mergeVirtualHostAttributes`，然后unocss将组件的属性渲染成css了，导致的尺寸过大，关闭这个属性即可。
