### ISSUE TITLE
关于响应拦截器中showMessage函数作用？

### ISSUE THREAD

**Issue by tcsuda** [oyjt/uniapp-vue3-template#33]
在 src/utils/request  功能中， 有使用到 showMessage 函数， 但是我没能明白，这个函数的作用， 可以解释一下吗？

**Comment by oyjt** [comment]
就是根据状态码，生成对应的错误信息

**Comment by tcsuda** [comment]
看功能是这样的， 但是我在 h5 以及 微信开发者工具 中， 都有测试， 都是不提示， 不晓得哪里问题

**Comment by oyjt** [comment]
状态码有两种，一种是接口请求成功之后返回的状态码（此时`statusCode=200`），项目中是`code`字段；另外一种是`statusCode`，属于`http`请求状态码，项目中`showMessage `函数只针对`statusCode != 200`的情况进行了处理

**Comment by tcsuda** [comment]
一个是  请求体， 一个是 响应头，我后端代码，是将 403 状态放在了 响应头中， 我测试 403 的接口， 不提示。   我对于前端属于初学，我知道 console.log打印在控制台， 或者是 dialog之类，这里的 showmessage是自己写的函数，如果功能是正常的， 应该是什么效果？ 在控制台显示？ 还是在页面弹窗一样的提示？

**Comment by oyjt** [comment]
> 一个是 响应体， 一个是 响应头，我后端代码，是将 403 状态放在了 响应头中， 我测试 403 的接口， 不提示。 我对于前端属于初学，我知道 console.log打印在控制台， 或者是 dialog之类，这里的 showmessage是自己写的函数，如果功能是正常的， 应该是什么效果？ 在控制台显示？ 还是在页面弹窗一样的提示？

如果正常，控制台会显示错误

**Comment by tcsuda** [comment]
这个函数返回的是字符串，是如何做到打印到控制台的？真搞不明白了，这里，程序进入到 HttpError流程中，但是不打印

**Comment by oyjt** [comment]
Promise.reject 会抛出错误，

> 这个函数返回的是字符串，是如何做到打印到控制台的？真搞不明白了，这里，程序进入到 HttpError流程中，但是不打印

实在抱歉，我这边代码的问题。发现代码中的`showMessage`确实没有打印出来，已经修复了，同步一下最新的代码就可以了。
给你造成的困扰实在抱歉，感谢用心的反馈。
