### ISSUE TITLE
feat: 增加一些常用特性

### ISSUE THREAD

**Issue by MelodyLLL** [oyjt/uniapp-vue3-template#38]
1. 建议可以丰富app.vue等文件，比如获取一些navbar高度等等封装到globaldata或者vuex等全局，这能极大便利使用者快速使用模版开发。
2. 可以增加获取用户信息并且存储的功能(需要考虑到调试时候的刷新)
3. 编写分支策略和代码贡献流程让更多人加入贡献

**Comment by syylike** [comment]
你有编译到支付宝小程序报错的问题吗

**Comment by oyjt** [comment]
1. 建议很不错，app.vue属于全局都会用的的东西，所以我加一些方法比较克制，后续有一些工具方法会优先放到utils中，另外全局是有用`pinia`存储数据的
2. 保存用户信息是有的，参考`pages`文件中的`login`页面，相关方法注释掉了，以及`store`文件夹中的`user`模块
3. 这个建议很不错，我会尽快落实

**Comment by MelodyLLL** [comment]
> 1. 建议很不错，app.vue属于全局都会用的的东西，所以我加一些方法比较克制，后续有一些工具方法会优先放到utils中，另外全局是有用`pinia`存储数据的
> 2. 保存用户信息是有的，参考`pages`文件中的`login`页面，相关方法注释掉了，以及`store`文件夹中的`user`模块
> 3. 这个建议很不错，我会尽快落实

非常认可你的思路，这也是为啥我关注这个项目的原因，因为够简洁技术栈够新。相教之前的package.json我看见你减少了很多东西，这个很棒，个人认为可以添加一些原生又实用的东西，三方依赖等谨慎加或尽量不加，less is more,  是这类项目最重要的一点。小程序市场感觉目前还是不错的，我觉得这个项目还是有可为的。另感谢作者对开源的贡献。

**Comment by oyjt** [comment]
感谢认可，欢迎多提`PR`
