### ISSUE TITLE
pnpm install 一直报依赖下不下来

### ISSUE THREAD

**Issue by Sdh-ui** [oyjt/uniapp-vue3-template#39]
pnpm install 一直报依赖下不下来，尝试了很多方法，包括pnpm缓存清除，node_modules删除重装还是不行
gifsicle 这个依赖主要是为了干啥的
.../gifsicle@5.2.0/node_modules/gifsicle postinstall$ node lib/install.js
│   ‼ getaddrinfo ENOENT raw.githubusercontent.com
│   ‼ gifsicle pre-build test failed
│   i compiling from source
│   × Error: Command failed: C:\Windows\system32\cmd.exe /s /c "autoreconf -ivf"
│ 'autoreconf' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
│ ���������ļ���
│     at D:\ProgramFiles\gitee\qianliang-user\node_modules\.pnpm\execa@0.7.0\node_modules\execa\index.js:231:11
│     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
│     at async Promise.all (index 0)
└─ Failed in 9s at D:\ProgramFiles\gitee\qianliang-user\node_modules\.pnpm\gifsicle@5.2.0\node_modules\gifsicle
node_modules/.pnpm/jpegtran-bin@5.0.2/node_modules/jpegtran-bin: Running postinstall script...
node_modules/.pnpm/esbuild@0.23.1/node_modules/esbuild: Running postinstall script, done in 2.7s
node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild: Running postinstall script, done in 2.2s
node_modules/.pnpm/optipng-bin@7.0.1/node_modules/optipng-bin: Running postinstall script...
node_modules/.pnpm/jpegtran-bin@6.0.1/node_modules/jpegtran-bin: Running postinstall script...
node_modules/.pnpm/mozjpeg@7.1.1/node_modules/mozjpeg: Running postinstall script...
 ELIFECYCLE  Command failed with exit code 1.
node_modules/.pnpm/cwebp-bin@6.1.2/node_modules/cwebp-bin: Running postinstall script...

**Comment by syylike** [comment]
https://blog.csdn.net/Fantasywt/article/details/132673024
你看下这个

**Comment by oyjt** [comment]
参考这个问题的回答 #23

**Comment by Sdh-ui** [comment]
> 参考这个问题的回答 #23

好的，谢谢！
