### ISSUE TITLE
ts提示问题

### ISSUE THREAD

**Issue by superBiuBiuMan** [oyjt/uniapp-vue3-template#43]
![image](https://github.com/user-attachments/assets/1f0e6a9d-6a2e-43de-acde-8015a1c9ceb2)
![image](https://github.com/user-attachments/assets/a1f52e12-469f-4d4c-85dc-ad02881620d6)
经常这样子,类型也指定了

**Comment by oyjt** [comment]
项目是自动引入类型，不需要再去引入。
另外使用的是`vscode`吗？如果是`webstorm`参考这里解决(https://juejin.cn/post/6930093893836865544)[https://juejin.cn/post/6930093893836865544]
