### ISSUE TITLE
支付宝小程序真机调用setInfo会报堆栈溢出

### ISSUE THREAD

**Issue by syylike** [oyjt/uniapp-vue3-template#44]
await userStore.setInfo({
      userId: res.user.user_id.toString(),
      userName: res.user.nick_name.toString(),
      avatar: res.user.avatar_url.toString(),
      mobile: res.user.mobile.toString(),
      isVip: res.user.is_vip.toString(),
    }) 
// 设置用户的信息
    setInfo(partial: Partial<UserState>) {
      try {
        this.$patch(partial)
        console.log('传入的参数:', partial)
        console.log('当前的 store 状态:', this.$state)
      }
      catch (error) {
        console.log('当前的 store 状态:', this.$state)
        console.error('更新用户信息失败:', error)
      }
    },
会打印出：更新用户信息失败: RangeError: Maximum call stack size exceeded
有没有大佬救救我

**Comment by oyjt** [comment]
`setInfo`不使用`this.$patch`改成传统的写法试试

**Comment by oyjt** [comment]
- 之前有人提到`pinia-plugin-persistedstate`版本太高会导致在支付宝小程序报错，降到`3.2.2`版本试试。
- 如果降版本不行，试试`setInfo`方法中不使用`this.$patch`方法改成传统的写法。
