### ISSUE TITLE
Illegal read directory error when using ShadCn

### ISSUE THREAD

**Issue by 0x67** [oyjt/uniapp-vue3-template#49]
Hello, I just tried your template and setting up [shadcn](https://www.shadcn-vue.com/)

And when I install the components and use it I get error `[vite] [plugin:vite:vue] EISDIR: illegal operation on a directory,`. I know it's probably not directly related to your actual template but UniApp implementation or something. However I'm not a native Chinese speaker and don't know where to look for this but my company also use UniApp. 

I can provide reproducible repo if you want. Any guidance or help regarding this issue would be helpful.

Edit: I'm on Windows 10/11

**Comment by oyjt** [comment]
It looks like it's caused by incorrectly referencing the component.
Sure, You can provide a repo.

**Comment by oyjt** [comment]
Try integrating `shadcn-ui`, refer to this [feature/shadcn-ui](https://github.com/oyjt/uniapp-vue3-template/tree/feature/shadcn-ui) branch to try
