### ISSUE TITLE
关于 https 本地开发

### ISSUE THREAD

**Issue by TrueRux** [oyjt/uniapp-vue3-template#51]
建议在项目里增加 https 本地开发，这个也很常用，例如本地（H5端）调用录音、摄像头等操作。

**Comment by oyjt** [comment]
感谢建议，这两个功能直接调用系统`api`就能实现，插件市场也有不少相关的插件，会增加项目的复杂度。
现阶段只是将项目作为简单的模板，后续如果考虑做大而全，肯能才会集成这些常用的功能。

**Comment by TrueRux** [comment]
对，的确找到不少插件。项目肯定能做大做全的👍
