### ISSUE TITLE
编译抖音小程序的时候遇到了一个问题 ，暂时解决不了 特来求助作者。

### ISSUE THREAD

**Issue by csh0101** [oyjt/uniapp-vue3-template#7]
"isInSSRComponentSetup" is not exported by "node_modules/.pnpm/vue@3.2.47/node_modules/vue/dist/vue.runtime.esm-bundler.js", imported by "node_modules/.pnpm/@dcloudio+uni-app@3.0.0-3090920231225001_@dcloudio+types@3.4.8_postcss@8.4.35_vue@3.2.47/node_modules/@dcloudio/uni-app/dist/uni-app.es.js".
at ../node_modules/.pnpm/@dcloudio+uni-app@3.0.0-3090920231225001_@dcloudio+types@3.4.8_postcss@8.4.35_vue@3.2.47/node_modules/@dcloudio/uni-app/dist/uni-app.es.js:1:46 
配置  "dev:mp-toutiao": "uni -p mp-toutiao" 并且 的时候出现了如上问题，根据我的观察 build/index.ts里面是有配置的uni的 
https://ask.dcloud.net.cn/question/180290
因此我对此感到疑惑。

**Comment by oyjt** [comment]
可能是uniapp的bug，更新uniapp依赖试试。

**Comment by oyjt** [comment]
更新相关依赖试试
